Project_2_Inferno/force-app/main/default/objects/Account/fields/Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Card_Status__c</fullName>
    <label>Card Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/force-app/main/default/classes/AccountTriggerHelper.cls
public class AccountTriggerHelper {
    public static void updateMembershipStatus(Account a) {
                if (a.Membership_Status__c == 'Active') {
                    if(a.Card_Status__c == 'Pending') {
                                 a.Membership_Status__c = 'Inactive';
                             }
                    if(a.Card_Status__c == 'Cancelled') {
                                 a.Membership_Status__c = 'Cancelled';
                             }
                }
    }
    public static void handleExpiredCard(Account a) {
        if(a.Membership_Status__c == 'Active'){
            if(a.Expiration_Date__c < date.today()) {
                ExpiredCardScheduler sch = new ExpiredCardScheduler();
                List<String> cronExpression = cronGenerator.createCron(a);
                String jobName = a.Email__c;
                Id scheduleId = System.schedule(jobName, cronExpression[0], sch);
                    }
        }
    }
}