Project 2 Inferno/force-app/main/default/objects/Account/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project_2_Inferno/force-app/main/default/objects/Account/fields/Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Card_Status__c</fullName>
    <label>Card Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Account/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default, Visa, Master Card, Discover, American Express</fullName>
                <default>true</default>
                <label>Default, Visa, Master Card, Discover, American Express</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project_2_Inferno/Main/main/default/objects/Account/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>3</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Name_On_Card__c.field-meta.xml
<CustomField>
    <fullName>Name_On_Card__c</fullName>
    <label>Name On Card</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Creation of account; seems possibly redundant with CreatedBy standard field</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Month to Month</fullName>
            </value>
            <value>
                <fullName>1 year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Product2/fields/Service_Tiers__c.field-meta.xml
<CustomField>
    <fullName>Service_Tiers__c</fullName>
    <label>Service Tiers</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>


    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 2 Inferno/force-app/main/default/objects/Receipt__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Receipt__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>When this purchased subscription ends.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Receipt__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Would be master-detail, but product2 cannot be a master. Use triggers to get around this and auto-delete related receipts if a product is deleted.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

Project_2_Inferno/force-app/main/default/objects/Receipt__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>When this purchased subscription starts</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Project 2 Inferno/force-app/main/default/classes/ReceiptTriggerTests.cls
@isTest
private class ReceiptTriggerTests {
    @TestSetup
    static void makeData(){
        Account testAcc1 = new Account();
        Account testAcc2 = new Account();
        testAcc1.Name = 'Bill';
        testAcc1.Email__c = 'bill@example.org';
        testAcc1.Membership_Status__c = 'Active';
        testAcc1.Password__c = 'pass12345';
        testAcc1.Name_On_Card__c = 'Bill Dollar';
        testAcc1.Card_Number__c = '1111222233334444';
        testAcc1.Card_Type__c = 'Visa';
        testAcc1.CVV__c = '123';
        testAcc1.Expiration_Date__c = date.today().addDays(-1);
        testAcc1.Card_Status__c = 'Active';
        //testAcc1.BillingAddress = '123 Main Street, New York NY, 12345';
		
        
        testAcc2.Name = 'Boll';
        testAcc2.Email__c = 'boll@example.org';
        testAcc2.Membership_Status__c = 'Active';
        testAcc2.Password__c = 'pass12345';
        testAcc2.Name_On_Card__c = 'Boll Dillar';
        testAcc2.Card_Number__c = '2222333344445555';
        testAcc2.Card_Type__c = 'Visa';
        testAcc2.CVV__c = '234';
        testAcc2.Expiration_Date__c = date.today().addDays(-1);
        testAcc2.Card_Status__c = 'Active';
        //testAcc2.BillingAddress = '234 Main Street, New York NY, 12345';

        Product2 paymonth = new Product2();
        Product2 payyear = new Product2();
        
        paymonth.Service_Tiers__c = 'Pay';
        paymonth.Duration__c = 'Month to Month';
        paymonth.Name = 'paymonth';

        payyear.Service_Tiers__c = 'Pay';
        payyear.Duration__c = '1 year';
        payyear.Name = 'payyear';
        
        System.debug(testAcc1.Name);
        insert testAcc1;
        insert testAcc2;
        insert paymonth;
        insert payyear;
    }

    @isTest 
    static void testVerifyDatesPositive() {
        Test.startTest();
        List<Account> myaccs = [SELECT Id FROM Account];
        List<Product2> myprods = [SELECT Id, Duration__c FROM Product2];
        List<Receipt__c> myrecs = new List<Receipt__c>();
        for (Integer i = 0; i < 2; i++){
            Receipt__c rec = new Receipt__c();
            rec.Account__c = myaccs[i].Id;
            System.debug('Receipt account: '+rec.Account__r.Id);
            rec.Product__c = myprods[i].Id;
            rec.Start_Date__c = date.today();
            if(myprods[i].Duration__c == 'Month to Month'){
                System.debug('Month');
                rec.End_Date__c = date.today().addMonths(1);
            } else {
                System.debug('year');
                rec.End_Date__c = date.today().addYears(1);
            }
            
            myrecs.add(rec);
        }

        Database.SaveResult[] srlist = Database.insert(myrecs, false);
        
        
        for (Receipt__c rec : myrecs){
            System.debug(rec.Product__r.Duration__c);
            System.debug(rec.Start_Date__c.daysBetween(rec.End_Date__c));
        }

        for (Database.SaveResult sr : srlist){
            System.debug(sr.getErrors());
            System.assert(sr.isSuccess());
        }
        Test.stopTest();
        
    }

    @isTest
    static void testVerifyDatesNegative() {
        Test.startTest();
        List<Account> myaccs = [SELECT Id FROM Account];
        System.debug('How many accounts: '+myaccs.size());
        List<Product2> myprods = [SELECT Id, Duration__c FROM Product2];
        List<Receipt__c> myrecs = new List<Receipt__c>();
        for (Integer i = 0; i < 2; i++){
            Receipt__c rec = new Receipt__c();
            rec.Account__c = myaccs[i].Id;
            System.debug('Receipt account: '+rec.Account__r.Id);
            rec.Product__c = myprods[i].Id;
            rec.Start_Date__c = date.today();
            if(myprods[i].Duration__c == 'Month to Month'){
                System.debug('Month');
                rec.End_Date__c = date.today().addYears(1);
            } else {
                System.debug('year');
                rec.End_Date__c = date.today().addMonths(1);
            }
            
            myrecs.add(rec);
        }

        Database.SaveResult[] srlist = Database.insert(myrecs, false);
        
        
        for (Receipt__c rec : myrecs){
            System.debug(rec.Product__r.Duration__c);
            System.debug(rec.Start_Date__c.daysBetween(rec.End_Date__c));
        }

        for (Database.SaveResult sr : srlist){
            System.debug(sr.getErrors());
            System.assert(!sr.isSuccess());
        }
        Test.stopTest();
        
    }
}