Project 2 Inferno/force-app/main/default/objects/Account/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project_2_Inferno/force-app/main/default/objects/Account/fields/Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Card_Status__c</fullName>
    <label>Card Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Account/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default, Visa, Master Card, Discover, American Express</fullName>
                <default>true</default>
                <label>Default, Visa, Master Card, Discover, American Express</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project_2_Inferno/Main/main/default/objects/Account/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>3</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Name_On_Card__c.field-meta.xml
<CustomField>
    <fullName>Name_On_Card__c</fullName>
    <label>Name On Card</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 2 Inferno/branch-am/main/default/classes/AccountDataFactory.cls
@isTest
public class AccountDataFactory {
    public static List<Account> createAccounts(Integer n, String cardStatus, Date cardExpiration) {
        List<Account> newAccounts = new List<Account>();
        for(Integer i = 0; i < n ; i++){
         Account a = new Account(
            Name='Test Account ' + i, CVV__c='123', 
            Card_Number__c='1234123412341234', Card_Type__c='Visa', Email__c='test' + i + '@email.com', 
            Membership_Status__c='Active', Name_On_Card__c='Señor Test ' + i, 
            Password__c='bestPassword');
            a.Card_Status__c = cardStatus;
            a.Expiration_Date__c = cardExpiration;
            newAccounts.add(a);           
        }
    insert newAccounts;
    return newAccounts;
    }
}