Project 2 Inferno/force-app/main/default/objects/Account/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project_2_Inferno/force-app/main/default/objects/Account/fields/Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Card_Status__c</fullName>
    <label>Card Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Account/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default, Visa, Master Card, Discover, American Express</fullName>
                <default>true</default>
                <label>Default, Visa, Master Card, Discover, American Express</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project_2_Inferno/Main/main/default/objects/Account/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>3</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Name_On_Card__c.field-meta.xml
<CustomField>
    <fullName>Name_On_Card__c</fullName>
    <label>Name On Card</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Streaming_Content__c/Streaming_Content__c.object-meta.xml
<CustomObject>
    <label>Streaming Content</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Content Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Streaming Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project 2 Inferno/force-app/main/default/classes/signinAccountController.cls
public class signinAccountController {
    public signinAccountController() {

    }

    @AuraEnabled(cacheable=true)
    public static String getAccount(string email, string password){
        List<Account> acc = [SELECT Id, Name, Email__c, Membership_Status__c, 
            Password__c, Name_On_Card__c, Card_Number__c, Card_Type__c,
            CVV__c, Expiration_Date__c, Card_Status__c, BillingAddress
             FROM Account WHERE Email__c = :email];
        if(password == acc[0].Password__c){
            return (String)acc[0].Id;
        }
        else {return null;}
    }

    @AuraEnabled(cacheable=false)
    public static List<String> searchResults(string text){
        List<Streaming_Content__c> searchresults = new List<Streaming_Content__c>();
        text = String.escapeSingleQuotes(text);
        String querytext = '%'+text+'%';

        searchresults = [SELECT Id FROM Streaming_Content__c WHERE Title__c LIKE :querytext];
        List<String> resultidlist = new List<String>();
        for(Streaming_Content__c result : searchresults){
            resultidlist.add((String)result.Id);
        }
        return resultidlist;
        
    }
}