Project 2 Inferno/Main/main/default/objects/Streaming_Content__c/Streaming_Content__c.object-meta.xml
<CustomObject>
    <label>Streaming Content</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Content Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Streaming Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project_2_Inferno/force-app/main/default/objects/Streaming_Content__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Documentary</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>SciFi</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Streaming_Content__c/fields/Needs_Review__c.field-meta.xml
<CustomField>
    <fullName>Needs_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical issues have been reported if this is checked.</description>
    <label>Needs Review</label>
    <type>Checkbox</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Streaming_Content__c/fields/Recommended_Age_Audience__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Age_Audience__c</fullName>
    <label>Recommended Age Audience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>PG</fullName>
            </value>
            <value>
                <fullName>PG13</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>NC-17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Streaming_Content__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
            </value>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Streaming_Content__c/fields/Viewer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Viewer_Rating__c</fullName>
    <label>Viewer Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/force-app/main/default/classes/StreamingContentHelper.cls
public with sharing class StreamingContentHelper {
    public StreamingContentHelper() {

    }

    @AuraEnabled
    (cacheable = true)
    public static List<Streaming_Content__c> getMovieList (){
        try {
            return [SELECT ID, Title__c, Video_URL__c, Viewer_Rating__c, Genre__c, Needs_Review__c, Recommended_Age_Audience__c, Synopsis__c, Tier__c, Year__c
                    FROM Streaming_Content__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}