Project 2 Inferno/Main/main/default/objects/Case/fields/Case_Subject__c.field-meta.xml
<CustomField>
    <fullName>Case_Subject__c</fullName>
    <description>Possibly redundant with Subject standard field, but that is text instead of a picklist</description>
    <label>Case Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Video Quality</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Case/fields/Streaming_Content__c.field-meta.xml
<CustomField>
    <fullName>Streaming_Content__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Video to reference, if there&apos;s a problem with one</description>
    <label>Streaming Content</label>
    <referenceTo>Streaming_Content__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Streaming_Content__c/Streaming_Content__c.object-meta.xml
<CustomObject>
    <label>Streaming Content</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Content Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Streaming Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project 2 Inferno/Main/main/default/objects/Streaming_Content__c/fields/Needs_Review__c.field-meta.xml
<CustomField>
    <fullName>Needs_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical issues have been reported if this is checked.</description>
    <label>Needs Review</label>
    <type>Checkbox</type>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Streaming_Content__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
            </value>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/force-app/main/default/classes/CaseTrigger_Helper.cls
public with sharing class CaseTrigger_Helper {
    public CaseTrigger_Helper() {
    }

    //Ensure that a case is only created for
    //Streaming Content that the user can view
    public static void CheckAccountTier(List<Case> caseList){

        //Variables
        List<Product2> productList = [SELECT ID, Family FROM Product2];
        Streaming_Content__c complaintMovie;
        string complaintTier = 'Free';
        Product2 complaintProduct;
        ID complaintID;

        //For Every Case
            //Get the Case's Streaming content
            //Get the Product ID Associated with the case
            //Use the Product ID to find the Subscription
        for (Case c: caseList){
            complaintMovie = c.Streaming_Content__r;    
            complaintID = c.ProductId;
            for (Product2 p : productList){
                if (complaintID == p.Id){
                    complaintProduct = p;
                }
            }
            if (complaintProduct != null){
                complaintTier = complaintProduct.Family;
            }
            //If the Account is not of a correct Tier to view the Content
            //Mark the case with an error
            switch on complaintMovie.Tier__c {
                when 'Pay' {
                    if (complaintTier != 'Pay' && complaintTier != 'Premium'){
                        c.Streaming_Content__c.addError('You do not have access to that Streaming Content!');
                    }
                }
                when 'Premium' {
                    if (complaintTier != 'Premium'){
                        c.Streaming_Content__c.addError('You do not have access to that Premium Streaming Content!');
                    }
                }
                when else {
                    if (complaintMovie.Tier__c != 'Free'){
                        c.Streaming_Content__c.addError('Invalid Streaming Tier!');
                    }
                }
            }
        }
    }

    //Flag Streaming Content that's recieved numerous video quality reports
    public static void CheckVideoReports(List<Case> caseList){
        //Variables
        Integer complaints;
        Integer complaintLimit = 10;
        Streaming_Content__c caseVideo;

        //For Every Case
        //Check how many other cases have issue with the same video
        //Check how many cases have marked Video Quality as the issue
        for(Case c: caseList){
            complaints = 0;
            caseVideo = c.Streaming_Content__r;
            for (Case c2: caseList){
                if (c2.Streaming_Content__r == caseVideo){
                    if (c2.Case_Subject__c == 'Video Quality'){
                        complaints++;
                    }
                }
            }
            //If a video has enough complaints, mark for review
            if (complaints >= complaintLimit){
                caseVideo.Needs_Review__c = true;
            }
        }
    }
}