Project 2 Inferno/Main/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Month to Month</fullName>
            </value>
            <value>
                <fullName>1 year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 2 Inferno/Main/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>


    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 2 Inferno/Main/main/default/objects/Receipt__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>When this purchased subscription ends.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Project 2 Inferno/force-app/main/default/objects/Receipt__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Would be master-detail, but product2 cannot be a master. Use triggers to get around this and auto-delete related receipts if a product is deleted.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

Project_2_Inferno/force-app/main/default/objects/Receipt__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>When this purchased subscription starts</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Project 2 Inferno/force-app/main/default/classes/ReceiptTriggerHelper.cls
public with sharing class ReceiptTriggerHelper {
    public ReceiptTriggerHelper() {

    }

    public static void verifyDates(List<Receipt__c> newReceipts){
        for(Receipt__c rec : newReceipts){
            Product2 product = rec.Product__c;
            String v1 = 'Month-to-Month';
            if(product.Duration__c == v1){
                if((rec.Start_Date__c.daysBetween(rec.End_Date__c) < 28) || (rec.Start_Date__c.daysBetween(rec.End_Date__c) > 31) ){
                    rec.addError('Start/End Date and Product don\'t match up');
                }
            }

            String v2 = 'Annual';
            if(product.Duration__c == v2){
                if((rec.Start_Date__c.daysBetween(rec.End_Date__c) < 364) || (rec.Start_Date__c.daysBetween(rec.End_Date__c) > 367) ){
                    rec.addError('Start/End Date and Product don\'t match up');
                }
            }
        }

    }
}